'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17020
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConsoleEnigmaMachine.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;rotormappings&gt;
        '''&lt;rotor position=&quot;1&quot; notches=&quot;Q&quot;&gt;
        '''&lt;mapping source=&quot;A&quot; destination=&quot;E&quot; /&gt;
        '''&lt;mapping source=&quot;B&quot; destination=&quot;K&quot; /&gt;
        '''&lt;mapping source=&quot;C&quot; destination=&quot;M&quot; /&gt;
        '''&lt;mapping source=&quot;D&quot; destination=&quot;F&quot; /&gt;
        '''&lt;mapping source=&quot;E&quot; destination=&quot;L&quot; /&gt;
        '''&lt;mapping source=&quot;F&quot; destination=&quot;G&quot; /&gt;
        '''&lt;mapping source=&quot;G&quot; destination=&quot;D&quot; /&gt;
        '''&lt;mapping source=&quot;H&quot; destination=&quot;Q&quot; /&gt;
        '''&lt;mapping source=&quot;I&quot; destination=&quot;V&quot; /&gt;
        '''&lt;mapping source=&quot;J&quot; destination=&quot;Z&quot; /&gt;
        '''&lt;mapping source=&quot;K&quot; destination=&quot;N&quot; /&gt;
        '''&lt;mapping source=&quot;L&quot; d [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property German123() As String
            Get
                Return ResourceManager.GetString("German123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;reflector&gt;
        '''&lt;mapping source=&quot;A&quot; destination=&quot;Y&quot; /&gt;
        '''&lt;mapping source=&quot;B&quot; destination=&quot;R&quot; /&gt;
        '''&lt;mapping source=&quot;C&quot; destination=&quot;U&quot; /&gt;
        '''&lt;mapping source=&quot;D&quot; destination=&quot;H&quot; /&gt;
        '''&lt;mapping source=&quot;E&quot; destination=&quot;Q&quot; /&gt;
        '''&lt;mapping source=&quot;F&quot; destination=&quot;S&quot; /&gt;
        '''&lt;mapping source=&quot;G&quot; destination=&quot;L&quot; /&gt;
        '''&lt;mapping source=&quot;H&quot; destination=&quot;D&quot; /&gt;
        '''&lt;mapping source=&quot;I&quot; destination=&quot;P&quot; /&gt;
        '''&lt;mapping source=&quot;J&quot; destination=&quot;X&quot; /&gt;
        '''&lt;mapping source=&quot;K&quot; destination=&quot;N&quot; /&gt;
        '''&lt;mapping source=&quot;L&quot; destination=&quot;G&quot; /&gt;
        '''&lt;mapping source=&quot;M&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ReflectorB() As String
            Get
                Return ResourceManager.GetString("ReflectorB", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
